/*
 * generated by Xtext 2.11.0
 */
package it.unica.tcs;

import it.unica.tcs.xsemantics.BitcoinTMStringRepresentation;
import it.xsemantics.runtime.StringRepresentation;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BitcoinTMRuntimeModule extends AbstractBitcoinTMRuntimeModule {
	
	/*
	 * custom implementation for xsemantics.
	 */
	public Class<? extends StringRepresentation> bindStringRepresentation() {
		return BitcoinTMStringRepresentation.class;
	}
}
