/*
 * Copyright 2017 Nicola Atzei
 */

/*
 * generated by Xtext 2.11.0
 */
package it.unica.tcs.tests

import com.google.inject.Inject
import it.unica.tcs.bitcoinTM.BitcoinTMFactory
import it.unica.tcs.bitcoinTM.Model
import it.unica.tcs.validation.IssueCodes
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(BitcoinTMInjectorProvider)
class BitcoinTMValidationTest {
    
    @Inject ParseHelper<Model> parseHelper
    @Inject ValidationTestHelper validatorHelper
    
    @Test
    def void transactionDeclaration() {
//      val result = parseHelper.parse('''
//          transaction T {
//              
//          }
//          
//          transaction T {
//              
//          }
//      ''')
//      Assert.assertNotNull(result)
//      Assert.assertTrue(result.eResource.errors.isEmpty)
//      
//      validatorHelper.assertError(
//          result.eResource, 
//          BitcoinTMFactory.eINSTANCE.createTransactionDeclaration.eClass, 
//          IssueCodes.TRANSACTION_DECLARATION__DUPLICATED_NAME
//      )
    }
    
    @Test
    def void participantDeclaration() {
//      val result = parseHelper.parse('''
//          participant A {
//              
//          }
//          
//          participant A {
//              
//          }
//      ''')
//      Assert.assertNotNull(result)
//      Assert.assertTrue(result.eResource.errors.isEmpty)
//      
//      validatorHelper.assertError(
//          result.eResource, 
//          BitcoinTMFactory.eINSTANCE.createParticipant.eClass, 
//          IssueCodes.PARTICIPANT_DECLARATION__DUPLICATED_NAME
//      )
    }
}
