/*
 * Copyright 2017 Nicola Atzei
 */

/*
 * generated by Xtext 2.11.0
 */
package xyz.balzaclang.web

import com.google.inject.Guice
import com.google.inject.Injector
import xyz.balzaclang.BalzacRuntimeModule
import xyz.balzaclang.BalzacStandaloneSetup
import xyz.balzaclang.ide.BalzacIdeModule
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages in web applications.
 */
class BalzacWebSetup extends BalzacStandaloneSetup {

    override Injector createInjector() {
        return Guice.createInjector(Modules2.mixin(new BalzacRuntimeModule, new BalzacIdeModule, new BalzacWebModule))
    }

}
