/*
 * generated by Xtext 2.17.0
 */
package xyz.balzaclang.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class BalzacWebModule extends AbstractBalzacWebModule {
}
