/*
 * Copyright 2017 Nicola Atzei
 */

/*
 * generated by Xtext 2.11.0
 */
package xyz.balzaclang.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class BalzacWebModule extends AbstractBalzacWebModule {
}
