/*
 * Copyright 2019 Nicola Atzei
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * generated by Xtext 2.17.0
 */
package xyz.balzaclang.web

import com.google.inject.Guice
import com.google.inject.Injector
import org.eclipse.xtext.util.Modules2
import xyz.balzaclang.BalzacRuntimeModule
import xyz.balzaclang.BalzacStandaloneSetup
import xyz.balzaclang.ide.BalzacIdeModule

/**
 * Initialization support for running Xtext languages in web applications.
 */
class BalzacWebSetup extends BalzacStandaloneSetup {

    override Injector createInjector() {
        return Guice.createInjector(Modules2.mixin(new BalzacRuntimeModule, new BalzacIdeModule, new BalzacWebModule))
    }

}
