package it.unica.tcs.validation;

public interface IssueCodes {

	String TRANSACTION_DECLARATION__DUPLICATED_NAME = "TRANSACTION_DECLARATION__DUPLICATED_NAME";
	String PARTICIPANT_DECLARATION__DUPLICATED_NAME = "PARTICIPANT_DECLARATION__DUPLICATED_NAME";
}
