FROM tomcat:8-jdk17

LABEL maintainer="atzeinicola@gmail.com"

ADD xyz.balzaclang.balzac.web/target/*.war /usr/local/tomcat/webapps/

EXPOSE 8080

HEALTHCHECK CMD curl --fail http://localhost:8080/balzac/version || exit 1

CMD ["catalina.sh", "run"]
