FROM alpine:latest AS extractor
ARG BITCOIND_CONNECTOR_TAG=v0.16.0
ARG BITCOINJ_TAG=0.16.3-LIB
RUN apk add git
RUN echo "Cloning https://github.com/natzei/BitcoindConnector4J.git"
RUN git clone https://github.com/natzei/BitcoindConnector4J.git
RUN git -C BitcoindConnector4J checkout $BITCOIND_CONNECTOR_TAG
RUN echo "Cloning https://github.com/natzei/bitcoinj.git"
RUN git clone https://github.com/natzei/bitcoinj.git
RUN git -C bitcoinj checkout $BITCOINJ_TAG


FROM gradle:5.6-jdk8 AS dependencies
COPY --from=extractor BitcoindConnector4J BitcoindConnector4J
COPY --from=extractor bitcoinj bitcoinj
RUN apt-get -qq update
RUN apt-get -qq install -y protobuf-compiler
RUN gradle -p BitcoindConnector4J install -x test
RUN gradle -p bitcoinj install -x test


FROM maven:3.6-jdk-8-slim AS builder
COPY --from=dependencies /root/.m2/repository/ /root/.m2/repository/
COPY . /balzac/
WORKDIR /balzac/
RUN mvn -f xyz.balzaclang.balzac.lib install
RUN mvn -f xyz.balzaclang.balzac.parent -U clean install


FROM tomcat:latest
LABEL maintainer="atzeinicola@gmail.com"
COPY --from=builder balzac/xyz.balzaclang.balzac.web/target/*.war /usr/local/tomcat/webapps/
EXPOSE 8080
HEALTHCHECK CMD curl --fail http://localhost:8080/balzac/version || exit 1
CMD ["catalina.sh", "run"]
