/*
 * Copyright 2019 Nicola Atzei
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * generated by Xtext 2.12.0
 */
package xyz.balzaclang.tests

import com.google.inject.Inject
import xyz.balzaclang.balzac.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(BalzacInjectorProvider)
class BalzacParsingTest {
    @Inject
    ParseHelper<Model> parseHelper

    @Test
    def void loadModel() {
//      val result = parseHelper.parse('''
//          Hello Xtext!
//      ''')
//      Assert.assertNotNull(result)
//      Assert.assertTrue(result.eResource.errors.isEmpty)
    }
}
