/*
 * generated by Xtext 2.17.0
 */
package xyz.balzaclang.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import xyz.balzaclang.BalzacRuntimeModule
import xyz.balzaclang.BalzacStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BalzacIdeSetup extends BalzacStandaloneSetup {

    override createInjector() {
        Guice.createInjector(Modules2.mixin(new BalzacRuntimeModule, new BalzacIdeModule))
    }

}
