/*
 * generated by Xtext 2.14.0
 */
package xyz.balzaclang.ide

import com.google.inject.Guice
import xyz.balzaclang.BalzacRuntimeModule
import xyz.balzaclang.BalzacStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BalzacIdeSetup extends BalzacStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BalzacRuntimeModule, new BalzacIdeModule))
	}

}
