/*
 * Copyright 2017 Nicola Atzei
 */

/*
 * generated by Xtext 2.11.0
 */
package it.unica.tcs

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BalzacStandaloneSetup extends BalzacStandaloneSetupGenerated {

    def static void doSetup() {
        new BalzacStandaloneSetup().createInjectorAndDoEMFRegistration()
    }
}

