/*
 * Copyright 2017 Nicola Atzei
 */

/*
 * generated by Xtext 2.11.0
 */
package it.unica.tcs.ide


/**
 * Use this class to register ide components.
 */
class BitcoinTMIdeModule extends AbstractBitcoinTMIdeModule {
}
