/*
 * generated by Xtext 2.11.0
 */
package it.unica.tcs.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class BitcoinTMWebModule extends AbstractBitcoinTMWebModule {
}
